---
title: "2020 Lab Journal"
author: "Kelly Mistry"
date: "7/24/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


### 7/24/2020 

C++ introductory course from Codecademy is 61% completed. Notes from the first 5 sections (hello world, variables, conditionals & logic, loops and vectors):

* possible variables types are: int for integers, double for floating-point numbers, char for individual characters, string for sequence of characters, and bool for true/false
* for loop format is a little different from R, with the counter declared, the bounds of the coutner and the interval of the counter in 3 separate parts. Ex: for (int i = 0; i < vector.size(); i++) {operation}. The i++ means the counter advances by 1. 
* if else is very similar to R in terms of syntax
* using vectors requires adding the vector library at the top of the script with #include <vector>, and the type of variable in the vector is declared when the vector is created. Ex: std::vector<int> vector_name = {vector contents}
* to print both variables, plain text and have a line break: std::cout << variable_name << "text" << "\n"; 

**Cheatsheets for all of the course contents are here: https://www.codecademy.com/learn/learn-c-plus-plus/modules/learn-cpp-hello-world/cheatsheet**

Notes from Functions section:
* 

